# ref: https://github.com/actions/starter-workflows/blob/main/pages/static.yml

on:
  push:
    branches: ["main"]

# Specify permissions for `GITHUB_TOKEN`. Of note: if we specify *anything* here,
# we must specify *everything*, since:
# > If you specify the access for any of these permissions, all of those that
# > are not specified are set to none.
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
#
# In particular, `deploy-pages` requires `id-token: write` and `pages: write` per
# https://github.com/actions/deploy-pages/blob/main/README.md#usage
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download big files
        run: |
          (cd docs/arm/2025-04-30 && ./get)
      - name: Configure GitHub Pages
        # not sure what this *does* in steady-state, but it's present in the
        # default config and I don't care enough to be different.
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'  # because we didn't build to _site/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
